switch require statements to custom errors
ZakkMan/quests-nft pull request #25
Opened 2023-09-29 12:39 UTC by 0xZakk

#3

2023-10-08 13:15 UTC, dugdaniels requested changes
A couple issues with this one where the change from `require` to `if` needs your check logic to be updated.

2023-10-08 13:15 UTC, dugdaniels commented on src/Quest.sol
> +        if(_from == _ownerOf[_id]) revert InvalidFrom();
Since you're switching from a `require` to an `if` your logic needs to be reversed.

`_from != _ownerOf[_id]`

2023-10-08 13:15 UTC, dugdaniels commented on src/Quest.sol
> +        if(_to != address(0)) revert InvalidRecipient();
Same issue here.

`_to == address(0)`

2023-10-10 19:09 UTC, 0xZakk commented
@dugdaniels great catch!

I need to think through this more, because the tests didn't catch this. Transferring is limited to an admin, so these checks might not be necessary anyway.

2023-10-12 16:40 UTC, dugdaniels commented
@0xZakk Your Forge tests did catch this. You had a couple that were failing previously.

2023-10-18 15:40 UTC, merged